"""Criação das tabelas docente e agendamento

Revision ID: f918bf2093e8
Revises: 
Create Date: 2025-10-21 16:10:25.386643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f918bf2093e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_reserva', sa.String(length=100), nullable=False),
    sa.Column('sala', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('horario_inicio', sa.String(length=5), nullable=False),
    sa.Column('horario_fim', sa.String(length=5), nullable=False),
    sa.Column('finalidade', sa.Text(), nullable=False),
    sa.Column('solicitacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacao_admin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamento')
    op.drop_table('usuario')
    # ### end Alembic commands ###
