"""Adiciona coluna tipo ao Usuario (com server_default)

Revision ID: 40545c1fbc4d
Revises: 50e060c11d88
Create Date: 2025-11-12 12:52:30.307035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40545c1fbc4d'
down_revision = '50e060c11d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), server_default='Docente', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
